---
conf:
  grafana:
    database:
      ssl_mode: true
      ca_cert_path: /etc/mysql/certs/ca.crt
      client_key_path: /etc/mysql/certs/tls.key
      client_cert_path: /etc/mysql/certs/tls.crt
endpoints:
  grafana:
    host_fqdn_override:
      default:
        tls:
          secretName: grafana-tls-api
          issuerRef:
            name: ca-issuer
            kind: ClusterIssuer
manifests:
  certificates: true
...
